### ISSUE TITLE
Add MetalLB to expose Kubernetes resources as LoadBalancers

### ISSUE THREAD

**Issue by Zorlin** [application-research/estuary-hosted-infrastructure#21]
We need to install and setup MetalLB to allow us to expose Kubernetes resources such as PostgreSQL to public routing.

Steps
```[tasklist]
### Tasks
- [x] Define IP range
- [x] Install MetalLB
- [x] Create object for that IP range
- [x] Test
```

**Comment by Zorlin** [comment]
IP range will be 10.24.5.1 through 10.24.5.254

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: prod-pool-a
  namespace: metallb-system
spec:
  addresses:
  - 10.24.5.0/24
```

Installation:
`helm install metallb metallb/metallb -n metallb-system`
